[project]
port = "9090"
# local
oss-type = ""

[Zap]
# debug info warn error dpanic panic fatal
level = "info"
format = "console"
prefix = "[Test]"
director = "log"
showLine = true
encode-level = "LowercaseColorLevelEncoder"
stacktrace-key = "stacktrace"
log-in-console = true
