project:
  port: "9090"
  # local aliyun-oss qiniu TencentCOS
  oss-type: "local"
  relative-path: "/v1"

Zap:
  # debug info warn error dpanic panic fatal
  level: "info"
  format: "console"
  prefix: "[Test]"
  director: "log"
  showLine: true
  # CapitalLevelEncoder:大写编码器 CapitalColorLevelEncoder:大写编码器带颜色
  # LowercaseLevelEncoder:小写编码器 LowercaseColorLevelEncoder:小写编码器
  encode-level: "CapitalColorLevelEncoder"
  stacktrace-key: "stacktrace"
  log-in-console: true

sql:
  mysql-config:
    hostname: "localhost"
    port: "3306"
    username: "root"
    password: "824196"
    dbname: "blog"
  postgres-config:
    hostname: "localhost"
    port: "5432"
    username: "postgres"
    password: "824196"
    dbname: "test"
  gorm-config:
    sql-type: "mysql" # mysql postgresql
    log-mode: "info" # silent error warn info
    log-zap: true # 是否使用zap作为gorm的logger
    skip-default-transaction: false # 是否跳过默认事务
    table-prefix: "t_" # 表名前缀
    singular-table: false # 是否使用单数表名
    max-idle-conn: 10 # 空闲连接池中连接的最大数量
    max-open-conn: 100 # 打开数据库连接的最大数量

Redis:
  Addr: ""
  Password: ""
  DB: 0

QiNiuYun:
  AccessKey: ""
  SecretKey: ""
  BucketName: ""
  StorageZone: ""
  UseHTTPS: false
  UseCdnDomains: true
  CdnPath: ""
  date-path: true

Aliyun:
  Url: ""
  Endpoint: ""
  AccessKeyId: ""
  AccessKeySecret: ""
  BucketName: ""
  date-path: true

local:
  path: "file"
  date-path: true