basePath: /
info:
  contact: {}
  description: This is a sample Server pets
  title: Swagger Example API
  version: 0.0.1
paths:
  /base/test:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      security:
      - ApiKeyAuth: []
      summary: 测试test
      tags:
      - aaa
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
